### ISSUE TITLE
WindowsError: [Error 183] Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by DJMix-I-Can** [mrkodz2/mrkodz2.github.io#1]
How are you doing, I'm putting this issues on behalf of a reddit user.
When we tried to run this add-on in a Windows environment, we get the following error. I tested it on my Android phone & it opens up. Kodi 18.5 Windows 7 64Bit. Thanks.
![Kodzi4Error](https://user-images.githubusercontent.com/35236592/77018937-97e93080-6955-11ea-873f-12a5d01f441f.jpg)

**Comment by mrkodz2** [comment]
Heey thanks for bringing it to my attention, there was a python bug that I encountered, however it has been sorted now.

**Comment by DJMix-I-Can** [comment]
Thanks, it worked. Have a good one..
